apiVersion: v1
kind: Pod
metadata:
  name: p1
  labels:
    project: example
    application: c1
spec:
  containers:
    - name: c1
      image: docker.io/rkalluru/learnk8s:rhel9-bare
  

  ---

  apiVersion: v1
  kind: Pod
  metadata:
    name: p2
    labels:
      project: p2
      application: c2
  spec: 
    containers:
      - name: c2
        image: docker.io/rkalluru/learnk8s:rhel9-bare