apiVersion: v1
kind: Deployment
metadata:
  name: deployment-demo
  labels:
    project: example1
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabel:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.24