apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-demo
  labels:
    project: example1
    app: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx