kind: Pod
apiVersion: v1
metadata:
  name: envvar-demo
  labels:
    purpose: env
spec:
  containers:
    - name: demo
      image: docker.io/rkalluru/learnk8s:rhel9-bare
      env: 
      - name: DEMO_GRETTING
        value: "Hello"