apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-data
data:
  DEMO_GRETING: "Hello from the env"
  DEMO_FAREWELL: "Such a sweet sorrow"

---
kind: Pod
apiVersion: v1
metadata:
  name: envar-demo-cm
  labels:
    purpose: demonstrate-envars
spec:
  containers:
  - name: demo
    image: docker.io/rkalluru/learnk8s:rhel9-bare
    env:
    - name: DEMO_GREETING
      valueFrom:
        configMapKeyRef:
          name: sample-data
          key: DEMO_GREETING
    - name: DEMO_FAREWELL
      valueFrom:
        configMapKeyRef:
          name: sample-data
          key: DEMO_FAREWELL