  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: frontend
  data:
    CATALOGUE_HOST: "catalogue"
    CATALOGUE_PORT: "8080"
    USER_PORT: "8080"
    USER_HOST: "user"
    CART_HOST: "cart"
    CART_PORT: "8080"
    SHIPPING_HOST: "shipping"
    SHIPPING_PORT: "8080" 
    PAYMENT_HOST: "payment"
    PAYMENT_PORT: "8080"  

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels: 
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      containers:
      - name: frontend
        image: public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
        envFrom:
           - configMapRef:
              name: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  selector:
      component: frontend
  ports:
  - port: 80 # service port
    targetPort: 80 #nginx port
