
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
data:
  SHIPPING_HOST: "shipping" 
  CART_ENDPOINT: "cart" 
  DB_HOST: "mysql-dev.kommanuthala.store"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  labels:
    component: shipping
spec:
  replicas: 1
  selector: 
    matchLabels:
      component: shipping
  template:
    metadata:
      labels:
        component: shipping
    spec:
     containers:
      - name: shipping
        image:  public.ecr.aws/w8x4g9h7/roboshop-v3/shipping
        envFrom:
          - configMapRef:
              name: shipping